nohup: ignoring input
[2025-06-26 15:06:37 +0700] [1286943] [INFO] Starting gunicorn 23.0.0
[2025-06-26 15:06:37 +0700] [1286943] [INFO] Listening at: http://0.0.0.0:5000 (1286943)
[2025-06-26 15:06:37 +0700] [1286943] [INFO] Using worker: sync
[2025-06-26 15:06:37 +0700] [1286946] [INFO] Booting worker with pid: 1286946
[2025-06-26 15:08:52,971] ERROR in app: Exception on /list_galleries [POST]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ubuntu/faceapp/app.py", line 52, in list_galleries
    "Accesstoken": d["token"]
KeyError: 'token'
[2025-06-26 15:20:40 +0700] [1286946] [INFO] Worker exiting (pid: 1286946)
[2025-06-26 15:20:40 +0700] [1286943] [INFO] Handling signal: term
[2025-06-26 15:20:40 +0700] [1286943] [ERROR] Worker (pid:1286946) was sent SIGTERM!
[2025-06-26 15:20:40 +0700] [1286943] [INFO] Shutting down: Master
